name: 'opencv-cache'
description: 'download, build and cache opencv'
inputs:
  branch:
    description: 'branch to checkout default is 4.x'
    required: true
    default: '4.x'
  BUILD_LIST:
    description: 'List of feature to compile, the less features you select the smallest will be the image.'
    required: true
    default: 'core'
  NO_CONTRIB:
    description: 'Disable openCV contrib.'
    default: ''

#outputs:
#  time: # output will be available to future steps
#    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/main.bundle.js'
