name: 'opencv-cache-improved'
description: 'download, build and cache opencv from source'
author: 'Uriel Chemouni'
inputs:
  branch:
    description: 'branch to checkout default is 4.x'
    required: true
    default: '4.x'
  BUILD_opencv_python3:
    description: 'Build Python3'
    default: 'ON'
  WITH_GSTREAMER:
    description: 'Build GStreamer'
    default: 'ON'
  DO_SHRINK:
    description: 'redude the size of the image by removing samples and tests.'
    default: ''
  NO_CONTRIB:
    description: 'Disable openCV contrib.'
    default: ''

#outputs:
#  time: # output will be available to future steps
#    description: 'The current time after waiting'
branding:
  icon: 'hard-drive'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/main.bundle.js'
